site_name: ibepoBlog
repo_url: https://github.com/ibepo/doc2/

theme:
    name: material
    locale: en
    analytics: { gtag: "G-274394082" }
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - User Guide: user-guide/
    - Developer Guide: dev-guide/
    - About:
          - Release Notes: about/release-notes.md
          - Contributing: about/contributing.md
          - License: about/license.md
markdown_extensions:
    - toc:
          permalink: 
    - attr_list
    - def_list
    - tables
    - pymdownx.highlight:
          use_pygments: false
    - pymdownx.snippets
    - pymdownx.superfences

plugins:
    - search
    - autorefs
    - literate-nav:
          nav_file: README.md
          implicit_index: true
    - mkdocstrings:
          handlers:
              python:
                  options:
                      docstring_section_style: list
                      members_order: source
                      show_root_heading: true
                      show_source: false
                      show_signature_annotations: true
