# https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
site_name: kamehameha
theme:
    name: material
    palette:
        primary: blue grey
    language: zh
    icon:
        logo: material/library-shelves
    features:
        - navigation.expand
        - navigation.indexes
        - navigation.sections
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.instant
        - navigation.tracking
        - navigation.path
        - toc.follow
markdown_extensions:
    - attr_list
    - pymdownx.tabbed
    - nl2br
    - toc:
          permalink: "#"
          slugify: !!python/name:pymdownx.slugs.uslugify # 解决中文标题解析问题


    - admonition
    - codehilite:
          guess_lang: false
          linenums: false
    - footnotes
    - meta
    - def_list
    - pymdownx.arithmatex
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    # - pymdownx.emoji:
    # emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde
plugins:
    - search
    - roamlinks
      #- autolinks
    - exclude:
          glob:
              - "*.tmp"
              - "*.pdf"
              - "*.gz"
          regex:
              - '.*\.(tmp|bin|tar)$'
